### ISSUE TITLE
Please bump autoconf to 2.69

### ISSUE THREAD

**Issue by Yamakuzure** [haubi/newlib-cygwin#2]
Autoconf-2.64 got removed from the portage tree.

I therefore opened bug https://bugs.gentoo.org/644924 to bring it back, but knew that this was unlikely.

So I bumped locally to autoconf-2.69 in configure.ac and config/override.m4 and build a new library. The result was a successful build with a working library, hexdumps of the old and new dll didn't show significant changes.

Could you please officially bump autoconf requirement to version 2.69?

**Comment by haubi** [comment]
Well, this is not the official upstream repository for cygwin. For something official please send patches directly to cygwin-patches list instead: https://cygwin.com/lists.html
That being said: Bringing old autoconf to cygwin prefix is a matter of keywording only, but 2.64 has been removed recently, only 2.13 is still around. Would it work with autoconf-2.13?

**Comment by Yamakuzure** [comment]
The problem is, that configure.ac and config/override.m4 are explicitly requesting this exact version.

We can ask upstream to bump it, but the problem only exists with gentoo having removed the old (aka ancient) version from the tree.

And if I understand it correctly, this very version is specifically for gentoo prefixes.
That's why I thought this could be a good place.

This is some sort of "Middlestream". With Gentoo/Prefix as Downstream, and Cygwin as Upstream. :-)
... I know... silly me... ;-)
